import { globalFontFace } from "@vanilla-extract/css";

export const manofa = [
  globalFontFace("Manofa Condensed", {
    src: `url('/fonts/Manofa-Condensed.woff2') format('woff2'),
        url('/fonts/Manofa-Condensed.woff') format('woff')`,
    fontWeight: "normal",
    fontStyle: "normal",
    fontDisplay: "swap",
  }),
  globalFontFace("Manofa Condensed", {
    src: `url('/fonts/Manofa-CondensedLight.woff2') format('woff2'),
        url('/fonts/Manofa-CondensedLight.woff') format('woff')`,
    fontWeight: "300",
    fontStyle: "normal",
    fontDisplay: "swap",
  }),
  globalFontFace("Manofa Condensed", {
    src: `url('/fonts/Manofa-CondensedBoldItalic.woff2') format('woff2'),
        url('/fonts/Manofa-CondensedBoldItalic.woff') format('woff')`,
    fontWeight: "bold",
    fontStyle: "italic",
    fontDisplay: "swap",
  }),
  globalFontFace("Manofa Condensed", {
    src: `url('/fonts/Manofa-CondensedBold.woff2') format('woff2'),
        url('/fonts/Manofa-CondensedBold.woff') format('woff')`,
    fontWeight: "bold",
    fontStyle: "normal",
    fontDisplay: "swap",
  }),
  globalFontFace("Manofa Condensed", {
    src: `url('/fonts/Manofa-CondensedMedium.woff2') format('woff2'),
        url('/fonts/Manofa-CondensedMedium.woff') format('woff')`,
    fontWeight: "500",
    fontStyle: "normal",
    fontDisplay: "swap",
  }),
  globalFontFace("Manofa Condensed", {
    src: `url('/fonts/Manofa-CondensedItalic.woff2') format('woff2'),
        url('/fonts/Manofa-CondensedItalic.woff') format('woff')`,
    fontWeight: "normal",
    fontStyle: "italic",
    fontDisplay: "swap",
  }),
  globalFontFace("Manofa Condensed", {
    src: `url('/fonts/Manofa-CondensedMediumItalic.woff2') format('woff2'),
        url('/fonts/Manofa-CondensedMediumItalic.woff') format('woff')`,
    fontWeight: "500",
    fontStyle: "italic",
    fontDisplay: "swap",
  }),
  globalFontFace("Manofa Condensed", {
    src: `url('/fonts/Manofa-CondensedLightItalic.woff2') format('woff2'),
        url('/fonts/Manofa-CondensedLightItalic.woff') format('woff')`,
    fontWeight: "300",
    fontStyle: "italic",
    fontDisplay: "swap",
  }),

  globalFontFace("Manofa", {
    src: `url('/fonts/Manofa-BoldItalic.woff2') format('woff2'),
  url('/fonts/Manofa-BoldItalic.woff') format('woff')`,
    fontWeight: "bold",
    fontStyle: "italic",
    fontDisplay: "swap",
  }),
  globalFontFace("Manofa", {
    src: `url('/fonts/Manofa-Light.woff2') format('woff2'),
  url('/fonts/Manofa-Light.woff') format('woff')`,
    fontWeight: "300",
    fontStyle: "normal",
    fontDisplay: "swap",
  }),
  globalFontFace("Manofa", {
    src: `url('/fonts/Manofa-LightItalic.woff2') format('woff2'),
  url('/fonts/Manofa-LightItalic.woff') format('woff')`,
    fontWeight: "300",
    fontStyle: "italic",
    fontDisplay: "swap",
  }),
  globalFontFace("Manofa", {
    src: `url('/fonts/Manofa-Bold.woff2') format('woff2'),
  url('/fonts/Manofa-Bold.woff') format('woff')`,
    fontWeight: "bold",
    fontStyle: "normal",
    fontDisplay: "swap",
  }),
  globalFontFace("Manofa", {
    src: `url('/fonts/Manofa-Medium.woff2') format('woff2'),
  url('/fonts/Manofa-Medium.woff') format('woff')`,
    fontWeight: "500",
    fontStyle: "normal",
    fontDisplay: "swap",
  }),
  globalFontFace("Manofa", {
    src: `url('/fonts/Manofa-Italic.woff2') format('woff2'),
  url('/fonts/Manofa-Italic.woff') format('woff')`,
    fontWeight: "normal",
    fontStyle: "italic",
    fontDisplay: "swap",
  }),
  globalFontFace("Manofa", {
    src: `url('/fonts/Manofa-Regular.woff2') format('woff2'),
  url('/fonts/Manofa-Regular.woff') format('woff')`,
    fontWeight: "normal",
    fontStyle: "normal",
    fontDisplay: "swap",
  }),
  globalFontFace("Manofa", {
    src: `url('/fonts/Manofa-MediumItalic.woff2') format('woff2'),
  url('/fonts/Manofa-MediumItalic.woff') format('woff')`,
    fontWeight: "500",
    fontStyle: "italic",
    fontDisplay: "swap",
  }),
];
