/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Group } from "three";
import { GroupProps } from "@react-three/fiber";
import WebGL from "three/examples/jsm/capabilities/WebGL";

export default function Model({ ...props }: GroupProps) {
  const group = useRef<Group>(null);
  const { nodes, materials } = useGLTF("/model/rock.gltf") as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.88, 6.35, -1.18]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell065.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell065_1.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[6.98, -3.5, -4.96]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell066.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell066_1.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[-5.45, 6.06, -2.59]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell001_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell001_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[-2.35, 5.79, -3.99]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell002_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell002_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[3.92, -6.63, -1.49]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell003_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell003_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[8.28, -6.25, -2.88]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell004.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell004_1.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[-0.85, 2.43, 4.36]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell005.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell005_1.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[2.2, 6.24, 2.24]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell006_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell006_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[8.14, -1.97, -5.59]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell007.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell007_1.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[-0.59, -4.47, -7.43]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell008.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell008_1.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[0.54, -2.92, 7.27]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell009_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell009_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[4.96, 0.7, -3.67]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell010_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell010_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[1.85, 2.09, 7.32]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell011.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell011_1.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[6.84, -3.03, -3.36]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell012_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell012_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[0.37, -4.8, 4.86]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell013_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell013_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[6.83, 6.01, 0.78]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell014.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell014_1.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[7.37, -5.61, -5.71]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell015_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell015_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <mesh
        geometry={nodes.Stone_low_1_Stone_low_1_0_cell030.geometry}
        material={materials.Stone_Inner}
        position={[2.86, -2.59, -2.57]}
      />
      <group position={[3.65, 4.85, -4.34]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell017_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell017_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[7.35, -2.87, 0.18]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell018.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell018_1.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[-4.42, -5.99, 5.35]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell019.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell019_1.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[-2.2, -7.2, -10.49]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell020.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell020_1.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[3.92, -6.3, -7.31]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell021_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell021_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[6.1, 3.84, 1.92]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell022_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell022_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[4.83, 5.37, -1.84]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell023_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell023_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[3.37, -0.37, 6.16]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell024.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell024_1.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[5.7, 0.05, 3.77]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell025.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell025_1.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[-5.31, -4.18, -8.31]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell026.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell026_1.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[3.16, -3.15, -7.77]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell027.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell027_1.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[-4.25, -4.29, 0.1]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell028_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell028_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[-4.78, 1.88, -2.14]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell029_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell029_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[0.42, 7.63, 1.37]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell030_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell030_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[3.56, 1.81, 1.8]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell031_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell031_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[-1.39, 0.92, -2.88]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell032_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell032_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[-4.85, 6.05, -5.63]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell033_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell033_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[-3.97, 8.27, -1.96]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell034_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell034_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[-3.22, -3.1, 6.9]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell035_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell035_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[3.14, -3.61, 3.21]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell036_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell036_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[-4.52, 8.18, -4.43]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell037.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell037_1.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[1.31, 3.75, -3.97]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell038_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell038_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[-5.29, -2.76, -4.11]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell039_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell039_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[4.07, -0.95, -6.27]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell040_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell040_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[2.8, 3.65, 5.87]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell041_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell041_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[-2.29, -7.17, 6.52]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell042_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell042_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[-2.52, 6.73, 0.41]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell043.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell043_1.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[-4.33, -1.56, 3.76]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell044_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell044_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
      <group position={[5.94, -5.52, 1.2]}>
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell045_1.geometry}
          material={materials.Stone_Outer}
        />
        <mesh
          geometry={nodes.Stone_low_1_Stone_low_1_0_cell045_2.geometry}
          material={materials.Stone_Inner}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/model/rock.gltf");
