/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: LamedeFeu (https://sketchfab.com/lamedefeu)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/grey-knight-0885c00ffa75478e9c6abe6b0370d285
title: Grey Knight
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Group } from "three";
import { GroupProps } from "@react-three/fiber";

export function Model({ ...props }: GroupProps) {
  const group = useRef<Group>(null);
  const { nodes, materials } = useGLTF("/models/scene.gltf") as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.polySurface1125_CLOAK_0.geometry}
            material={materials.CLOAK}
          />
          <mesh
            geometry={nodes.polySurface1125_CHAR_0.geometry}
            material={materials.CHAR}
          />
          <mesh
            geometry={nodes.polySurface1119_WEAPON_0.geometry}
            material={materials.WEAPON}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/scene.gltf");
