/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Thomas Flynn (https://sketchfab.com/nebulousflynn)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/marble-torso-from-a-statue-of-dionysos-de078950bd474c73bb6cd7e1cf31de9b
title: Marble torso from a statue of Dionysos
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { LayerMaterial, Depth, Noise } from "lamina";
import * as THREE from "three";
import { Material } from "three";

const colorA = new THREE.Color("#000000").convertSRGBToLinear();
const colorB = new THREE.Color("#7d7d7d").convertSRGBToLinear();
const fresnel = new THREE.Color("#000dff").convertSRGBToLinear();

export function Bg() {
  return (
    <mesh scale={100}>
      <boxGeometry args={[1, 1, 1]} />
      <LayerMaterial side={THREE.BackSide}>
        <Depth
          colorB={colorA}
          colorA={colorB}
          alpha={1}
          mode="normal"
          near={130}
          far={200}
          origin={[100, 100, -100]}
        />
        <Noise
          mapping="local"
          type="white"
          scale={1000}
          colorA="white"
          colorB="black"
          mode="subtract"
          alpha={0.2}
        />
      </LayerMaterial>
    </mesh>
  );
}

export default function Model({ ...props }) {
  const { nodes } = useGLTF("/scene.gltf") as any;
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -10]} scale={1} rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry}></mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
