/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { Float, useGLTF } from "@react-three/drei";
import { Group } from "three";

export default function Phone({ ...props }) {
  const group = useRef<Group>(null);
  const { nodes, materials } = useGLTF("/iphone/iphone.gltf") as any;
  return (
    <group>
      <pointLight
        color="white"
        position={[4, 2, 2]}
        distance={30}
        intensity={4}
        castShadow
      />
      <pointLight
        color="blue"
        position={[-4, 3, -2]}
        distance={30}
        intensity={2}
        castShadow
      />
      <Float>
        <group ref={group} {...props} dispose={null}>
          <group position={[0, 1.56, 0]}>
            <mesh
              geometry={nodes.Circle038.geometry}
              material={materials["FrameGrey.001"]}
            />
            <mesh
              geometry={nodes.Circle038_1.geometry}
              material={materials["Front.001"]}
            />
            <mesh
              geometry={nodes.Circle038_2.geometry}
              material={materials["Antennaline.001"]}
            />
            <mesh
              geometry={nodes.Circle038_3.geometry}
              material={materials["BackGrey.001"]}
            />
            <mesh
              geometry={nodes.Circle038_4.geometry}
              material={materials["Rubber.001"]}
            />
            <mesh
              geometry={nodes.AntennaLineBottom001.geometry}
              material={materials["Antennaline.001"]}
              position={[0, -2.68, 0]}
            />
            <mesh
              geometry={nodes.AntennaLineTop001.geometry}
              material={materials["Antennaline.001"]}
              position={[0, 0.02, 0]}
            />
            <mesh
              geometry={nodes.AppleLogo001.geometry}
              material={materials["AppleLogo.001"]}
              position={[0.17, 0.52, -0.08]}
            />
            <mesh
              geometry={nodes.BackCameraBottomGreyRing001.geometry}
              material={materials["BackCaneraGrayRIng.002"]}
              position={[0.7, 0.88, -0.09]}
            />
            <mesh
              geometry={nodes.BackCameraBottomLens001.geometry}
              material={materials["Lens.001"]}
              position={[0.7, 0.88, -0.08]}
            />
            <mesh
              geometry={nodes.BackCameraP1001.geometry}
              material={materials["Black.015"]}
              position={[0.7, 1.03, -0.09]}
            />
            <mesh
              geometry={nodes.BackCameraTopGreyRing001.geometry}
              material={materials["BackCaneraGrayRIng.002"]}
              position={[0.7, 1.18, -0.09]}
            />
            <mesh
              geometry={nodes.BackCameraTopLens001.geometry}
              material={materials["Lens.001"]}
              position={[0.7, 1.18, -0.08]}
            />
            <mesh
              geometry={nodes.CameraBump001.geometry}
              material={materials["Frame.001"]}
              position={[0.7, 1.04, -0.08]}
            />
            <mesh
              geometry={nodes.FlashBG001.geometry}
              material={materials["PinkFlash.002"]}
              position={[0.71, 1.03, -0.09]}
            />
            <mesh
              geometry={nodes.FrontCameraContainer001.geometry}
              material={materials["FrontCameraBlack.002"]}
              position={[0.34, 1.32, 0.08]}
            />
            <mesh
              geometry={nodes.FrontSpeakerBG001.geometry}
              material={materials["FrontSpeaker.001"]}
              position={[0.16, 1.32, 0.08]}
            />
            <mesh
              geometry={nodes.iPhoneLogo001.geometry}
              material={materials["iPhoneLogo.001"]}
              position={[0.2, -1.18, -0.08]}
            />
            <mesh
              geometry={nodes.MuteSwitch001.geometry}
              material={materials["FrameGrey.001"]}
              position={[-0.65, 0.92, 0.01]}
            />
            <group position={[0.97, 0.56, 0]}>
              <mesh
                geometry={nodes.Circle032.geometry}
                material={materials["FrameGrey.001"]}
              />
              <mesh
                geometry={nodes.Circle032_1.geometry}
                material={materials["Frame.001"]}
              />
            </group>
            <group position={[0.98, -0.04, 0]}>
              <mesh
                geometry={nodes.Circle031.geometry}
                material={materials["Black.014"]}
              />
              <mesh
                geometry={nodes.Circle031_1.geometry}
                material={materials["FrameGrey.001"]}
              />
            </group>
            <mesh
              geometry={nodes.SCREEN.geometry}
              material={materials["Display.002"]}
            />
            <mesh
              geometry={nodes.VolumeButtons001.geometry}
              material={materials["FrameGrey.001"]}
              position={[-0.66, 0.21, 0]}
            />
          </group>
        </group>
      </Float>
    </group>
  );
}

useGLTF.preload("/iphone.gltf");
